// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Saas.Presentation.Provider.Web.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;
    using System.ComponentModel.DataAnnotations;

    public partial class Tenant
    {
        /// <summary>
        /// Initializes a new instance of the Tenant class.
        /// </summary>
        public Tenant() { }

        /// <summary>
        /// Initializes a new instance of the Tenant class.
        /// </summary>
        public Tenant(string name, int? productId = default(int?))
        {
            Name = name;
            ProductId = productId;
        }

        /// <summary>
        /// </summary>
        [Display(Name = "Company Name")]
        [Required]
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "productId")]
        public int? ProductId { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            if (Name == null)
            {
                throw new Microsoft.Rest.ValidationException(ValidationRules.CannotBeNull, "Name");
            }
        }
    }
}
