// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Saas.Presentation.Provider.Web.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class Tenant
    {
        /// <summary>
        /// Initializes a new instance of the Tenant class.
        /// </summary>
        public Tenant() { }

        /// <summary>
        /// Initializes a new instance of the Tenant class.
        /// </summary>
        public Tenant(string name = default(string), string type = default(string), string category = default(string), string region = default(string))
        {
            Name = name;
            Type = type;
            Category = category;
            Region = region;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "type")]
        public string Type { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "category")]
        public string Category { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "region")]
        public string Region { get; set; }

    }
}
